package main;

public class ExecutionFixParameters {
//	ParameterSet p_set = new ParameterSet();
//	p_set.setParam(IloCplex.IntParam.HeurFreq, cplex, -1);	
//	p_set.setParam(IloCplex.LongParam.HeurFreq, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.NodeAlg, IloCplex.Algorithm.Dual);
//	p_set.setParam(IloCplex.IntParam.RootAlg, IloCplex.Algorithm.Dual);
//	p_set.setParam(IloCplex.IntParam.SiftAlg, IloCplex.Algorithm.Dual);
//
//	p_set.setParam(IloCplex.LongParam.AggFill, 10);
//	p_set.setParam(IloCplex.LongParam.BarItLim, 2100000);
//	p_set.setParam(IloCplex.LongParam.BarMaxCor, 0);
//	p_set.setParam(IloCplex.LongParam.BBInterval, 0);
//	p_set.setParam(IloCplex.LongParam.CutPass, 300);
//	p_set.setParam(IloCplex.LongParam.FracPass, 10);
//	p_set.setParam(IloCplex.LongParam.HeurFreq, cplex, -1);
//	p_set.setParam(IloCplex.LongParam.IntSolLim, 2100000000);
//	p_set.setParam(IloCplex.LongParam.ItLim, 21000000);
//	
//	p_set.setParam(IloCplex.LongParam.MIPInterval, 100);
//	p_set.setParam(IloCplex.LongParam.NetItLim, 21000000);
//	p_set.setParam(IloCplex.LongParam.NodeLim, 2100000000);
//	p_set.setParam(IloCplex.LongParam.NzReadLim, 250000);
//	p_set.setParam(IloCplex.LongParam.PolishAfterIntSol,  2100000);
//	p_set.setParam(IloCplex.LongParam.PolishAfterNode, 210000000);
//	p_set.setParam(IloCplex.LongParam.QPNzReadLim, 5000);
//	p_set.setParam(IloCplex.LongParam.RepairTries, cplex, -1);
//	p_set.setParam(IloCplex.LongParam.RINSHeur, cplex, -1);
//	p_set.setParam(IloCplex.LongParam.SiftItLim, 2100000000);
//	p_set.setParam(IloCplex.LongParam.StrongItLim, 10);
//	p_set.setParam(IloCplex.LongParam.SubMIPNodeLim, 500);
//
//	p_set.setParam(IloCplex.IntParam.ZeroHalfCuts, 1);
//	p_set.setParam(IloCplex.BooleanParam.XXXInd, false);
//	p_set.setParam(IloCplex.IntParam.WriteLevel, 1);
//	p_set.setParam(IloCplex.DoubleParam.WorkMem, 128);
//	p_set.setParam(IloCplex.StringParam.WorkDir, ".");
//	p_set.setParam(IloCplex.IntParam.VarSel, cplex, -1);
////	p_set.setParam(IloCplex.DoubleParam.TuningDetTiLim, 1000);
//	p_set.setParam(IloCplex.DoubleParam.TuningTiLim, 10000);
//	p_set.setParam(IloCplex.IntParam.TuningRepeat, 1);
////Je ne sais pas comment le fixer		
////	p_set.setParam(IloCplex.IntParam.TuningMeasure, IloCplex.3);
//	p_set.setParam(IloCplex.IntParam.TuningDisplay, 3);
//	p_set.setParam(IloCplex.DoubleParam.TreLim, 1E75);
//	p_set.setParam(IloCplex.DoubleParam.TiLim, 1E75);
//	p_set.setParam(IloCplex.IntParam.Threads, 1);
//	p_set.setParam(IloCplex.IntParam.Symmetry, 0);
//	p_set.setParam(IloCplex.IntParam.SubMIPNodeLim, 500);
//	p_set.setParam(IloCplex.IntParam.StrongItLim, 10);
//	p_set.setParam(IloCplex.IntParam.StrongCandLim, 10);
//	p_set.setParam(IloCplex.IntParam.SolutionTarget, 1);
//	p_set.setParam(IloCplex.IntParam.SolnPoolReplace, 0);
//	p_set.setParam(IloCplex.IntParam.SolnPoolIntensity, 1);
//	p_set.setParam(IloCplex.DoubleParam.SolnPoolGap, 1E75);
//	p_set.setParam(IloCplex.IntParam.SolnPoolCapacity, 21000000);
//	p_set.setParam(IloCplex.DoubleParam.SolnPoolAGap, 1E75);
//	p_set.setParam(IloCplex.IntParam.SingLim, 10);
//	p_set.setParam(IloCplex.IntParam.SimDisplay, 2);
//	p_set.setParam(IloCplex.IntParam.SiftItLim, 21000000);
//	p_set.setParam(IloCplex.IntParam.SiftDisplay, 2);
//	p_set.setParam(IloCplex.IntParam.ScaInd, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.RowReadLim, 30000);
//	p_set.setParam(IloCplex.IntParam.RINSHeur, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.RepeatPresolve, 0);
//	p_set.setParam(IloCplex.IntParam.RepairTries, cplex, -1);
//	p_set.setParam(IloCplex.DoubleParam.RelObjDif, 0.0);
//	p_set.setParam(IloCplex.IntParam.RelaxPreInd, 0);
//	p_set.setParam(IloCplex.IntParam.ReInv, 100);
//	p_set.setParam(IloCplex.IntParam.RandomSeed, 100);
//	p_set.setParam(IloCplex.IntParam.QPNzReadLim, 5000);
//	p_set.setParam(IloCplex.BooleanParam.QPmakePSDInd, true);
//	p_set.setParam(IloCplex.DoubleParam.ProbeTime, 1E75);
//	p_set.setParam(IloCplex.IntParam.Probe, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.PriceLim, 10);
//	p_set.setParam(IloCplex.IntParam.PreslvNd, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.PrePass, 0);
//	p_set.setParam(IloCplex.BooleanParam.PreLinear, false);
//	p_set.setParam(IloCplex.BooleanParam.PreInd, true);
//	p_set.setParam(IloCplex.IntParam.PreDual, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.PPriInd, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.PopulateLim, 20);
//	p_set.setParam(IloCplex.DoubleParam.PolishTime, 20);
//	p_set.setParam(IloCplex.DoubleParam.PolishTime, 0.0);
//	p_set.setParam(IloCplex.DoubleParam.PolishAfterTime, 1E75);
//	p_set.setParam(IloCplex.DoubleParam.PolishAfterDetTime, 1E75);
//	p_set.setParam(IloCplex.IntParam.PolishAfterNode, 21000000);
//	p_set.setParam(IloCplex.IntParam.PolishAfterIntSol, 21000000);
//	p_set.setParam(IloCplex.DoubleParam.PolishAfterEpGap, 0.0);
//	p_set.setParam(IloCplex.DoubleParam.PolishAfterEpAGap, 0.0);
//	p_set.setParam(IloCplex.IntParam.PerLim, 50);
//	p_set.setParam(IloCplex.BooleanParam.PerInd, true);
//	p_set.setParam(IloCplex.IntParam.ParallelMode, 1);
//	p_set.setParam(IloCplex.DoubleParam.ObjULim, 1E75);
//	p_set.setParam(IloCplex.DoubleParam.ObjLLim, cplex, -1E75);
//	p_set.setParam(IloCplex.DoubleParam.ObjDif, 0.0);
//	p_set.setParam(IloCplex.IntParam.NzReadLim, 250000);
//	p_set.setParam(IloCplex.BooleanParam.NumericalEmphasis, false);
//	p_set.setParam(IloCplex.IntParam.NodeSel, 2);
//	p_set.setParam(IloCplex.IntParam.NodeLim, 2100000000);
//	p_set.setParam(IloCplex.IntParam.NodeFileInd, 1);
//	p_set.setParam(IloCplex.IntParam.NetPPriInd, 1);
//	p_set.setParam(IloCplex.IntParam.NetItLim, 210000000);
//	p_set.setParam(IloCplex.IntParam.NetFind, 1);
//	p_set.setParam(IloCplex.DoubleParam.NetEpRHS, 1e-6);
//	p_set.setParam(IloCplex.DoubleParam.NetEpOpt, 1e-6);
//	p_set.setParam(IloCplex.IntParam.NetDisplay, 2);
//	p_set.setParam(IloCplex.BooleanParam.MPSLongNum, true);
//	p_set.setParam(IloCplex.IntParam.MIRCuts, 1);
//	p_set.setParam(IloCplex.IntParam.MIQCPStrat, 1);
//	p_set.setParam(IloCplex.IntParam.MIPSearch, 1);
//	p_set.setParam(IloCplex.IntParam.MIPKappaStats, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.MIPOrdType, 0);
//	p_set.setParam(IloCplex.BooleanParam.MIPOrdInd, false);
//	p_set.setParam(IloCplex.IntParam.MIPInterval, 100);
//	p_set.setParam(IloCplex.IntParam.MIPEmphasis, 1);
//	p_set.setParam(IloCplex.IntParam.MIPDisplay, 0);
//	//TODO Regarder ce qu'affiche cplex (et du coup desactiver le param juste au dessus)
//	p_set.setParam(IloCplex.BooleanParam.MemoryEmphasis, false);
//	p_set.setParam(IloCplex.IntParam.MIPSearch, 1);
//	p_set.setParam(IloCplex.IntParam.MCFCuts, 1);
//	p_set.setParam(IloCplex.BooleanParam.LBHeur, false);
//	p_set.setParam(IloCplex.IntParam.ItLim, 2100000000);
//	p_set.setParam(IloCplex.IntParam.IntSolLim, 2100000000);
//	p_set.setParam(IloCplex.IntParam.ImplBd, 1);
//	p_set.setParam(IloCplex.IntParam.GUBCovers, 1);
//	p_set.setParam(IloCplex.IntParam.FracPass, 10);
//	p_set.setParam(IloCplex.IntParam.FracCuts, 1);
//	p_set.setParam(IloCplex.IntParam.FracCand, 200);
//	p_set.setParam(IloCplex.IntParam.FlowPaths, 1);
//	p_set.setParam(IloCplex.IntParam.FlowCovers, 1);
//	p_set.setParam(IloCplex.IntParam.FPHeur, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.FeasOptMode, 0);
//	p_set.setParam(IloCplex.DoubleParam.EpRHS, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpRelax, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpPer, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpOpt, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpMrk, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpLin, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpInt, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpAGap, 1E-4);
//	p_set.setParam(IloCplex.DoubleParam.EpGap, 1E-4);
//	p_set.setParam(IloCplex.IntParam.EachCutLim, 21000000);
//	p_set.setParam(IloCplex.IntParam.DPriInd, 1);
//	p_set.setParam(IloCplex.IntParam.DiveType, 1);
//	p_set.setParam(IloCplex.IntParam.DisjCuts, 1);
//	p_set.setParam(IloCplex.DoubleParam.DetTiLim, 210000000);
//	p_set.setParam(IloCplex.IntParam.DepInd, 0);
//	p_set.setParam(IloCplex.BooleanParam.DataCheck, false);
//	p_set.setParam(IloCplex.DoubleParam.CutUp, 1E75);
////	p_set.setParam(IloCplex.DoubleParam.CutsFactor, 4);
//	p_set.setParam(IloCplex.IntParam.CutPass, 300);
//	p_set.setParam(IloCplex.DoubleParam.CutLo, cplex, -1E+75);
//	p_set.setParam(IloCplex.IntParam.CraInd, cplex, -1);
//	p_set.setParam(IloCplex.IntParam.Covers, 1);
//	p_set.setParam(IloCplex.IntParam.ConflictDisplay, 2);
//	p_set.setParam(IloCplex.IntParam.ColReadLim, 60000);
//	p_set.setParam(IloCplex.IntParam.CoeRedInd, 0);
//	p_set.setParam(IloCplex.IntParam.ClockType, 2);
//	p_set.setParam(IloCplex.BooleanParam.CloneLog, true);
//	p_set.setParam(IloCplex.IntParam.Cliques, 1);
//	p_set.setParam(IloCplex.DoubleParam.BtTol, 0.9);
//	//Seems to be a good strategy
//	p_set.setParam(IloCplex.IntParam.BrDir, 0);
//	p_set.setParam(IloCplex.IntParam.BndStrenInd, 0);
//	p_set.setParam(IloCplex.IntParam.BBInterval, 0);
//	p_set.setParam(IloCplex.IntParam.BarStartAlg, 1);
//	p_set.setParam(IloCplex.IntParam.BarOrder, 1);
//	p_set.setParam(IloCplex.DoubleParam.BarQCPEpComp, 1E-7);
//	p_set.setParam(IloCplex.DoubleParam.BarObjRng, 1e20);
//	p_set.setParam(IloCplex.IntParam.BarMaxCor, 0);
//	p_set.setParam(IloCplex.IntParam.BarItLim, 2100000);
//	p_set.setParam(IloCplex.DoubleParam.BarGrowth, 1E12);
//	p_set.setParam(IloCplex.DoubleParam.BarEpComp, 1E-8);
//	p_set.setParam(IloCplex.IntParam.BarDisplay, 2);
//	p_set.setParam(IloCplex.IntParam.BarCrossAlg, 1);
//	p_set.setParam(IloCplex.IntParam.BarColNz, 10);
//	p_set.setParam(IloCplex.IntParam.BarAlg, 3);
//	p_set.setParam(IloCplex.IntParam.AuxRootThreads, 0);
//	p_set.setParam(IloCplex.IntParam.AggInd, 0);
//	p_set.setParam(IloCplex.IntParam.AggFill, 10);
//	p_set.setParam(IloCplex.IntParam.AggCutLim,3);
//	p_set.setParam(IloCplex.IntParam.AdvInd, 0);

}
